//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverFlow_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StackoverflowEntities : DbContext
    {
        public StackoverflowEntities()
            : base("name=StackoverflowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Soru> Soru { get; set; }
        public virtual DbSet<Cevap> Cevap { get; set; }
    
        public virtual int SoruSil(Nullable<int> qID)
        {
            var qIDParameter = qID.HasValue ?
                new ObjectParameter("qID", qID) :
                new ObjectParameter("qID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SoruSil", qIDParameter);
        }
    
        public virtual int CevapSil(Nullable<int> aID)
        {
            var aIDParameter = aID.HasValue ?
                new ObjectParameter("aID", aID) :
                new ObjectParameter("aID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CevapSil", aIDParameter);
        }
    }
}
